kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: magichome-aws-iot
  labels:
    name: magichome-aws-iot
spec:
  replicas: 1
  selector:
    matchLabels:
      name: magichome-aws-iot
  template:
    metadata:
      labels:
        name: magichome-aws-iot
    spec:
      hostNetwork: true
      containers:      
      - image: chrisns/iot-magichome
        name: magichome-aws-iot
        imagePullPolicy: Always
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-iot-creds
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-iot-creds
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_IOT_ENDPOINT_HOST
            valueFrom:
              secretKeyRef:
                name: aws-iot-creds
                key: AWS_IOT_ENDPOINT_HOST
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: aws-iot-creds
                key: AWS_REGION
      restartPolicy: Always