kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
