kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: nfs
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nfs
            - name: NFS_SERVER
              value: ilium.p.cns.me
            - name: NFS_PATH
              value: /volume2/cluster-store
      volumes:
        - name: nfs-client-root
          nfs:
            server: ilium.p.cns.me
            path: /volume2/cluster-store