apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml

secretGenerator:
  - name: nest
    env: env.txt
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true

namespace: nest