kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: velux-aws-iot
  labels:
    name: velux-aws-iot
spec:
  replicas: 1
  selector:
    matchLabels:
      name: velux-aws-iot
  template:
    metadata:
      labels:
        name: velux-aws-iot
    spec:
      containers:
      - image: chrisns/iot_velux
        name: velux-aws-iot
        imagePullPolicy: Always
        env:
          - name: VELUX_ADDRESS
            valueFrom:
              secretKeyRef:
                name: velux
                key: VELUX_ADDRESS
          - name: VELUX_PASSWORD
            valueFrom:
              secretKeyRef:
                name: velux
                key: VELUX_PASSWORD
          - name: VELUX_TOPIC
            valueFrom:
              secretKeyRef:
                name: velux
                key: VELUX_TOPIC
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-iot-creds
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-iot-creds
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_IOT_ENDPOINT_HOST
            valueFrom:
              secretKeyRef:
                name: aws-iot-creds
                key: AWS_IOT_ENDPOINT_HOST
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: aws-iot-creds
                key: AWS_REGION
      restartPolicy: Always