kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: velux-aws-iot
  labels:
    name: velux-aws-iot
spec:
  replicas: 1
  selector:
    matchLabels:
      name: velux-aws-iot
  template:
    metadata:
      labels:
        name: velux-aws-iot
      annotations:
        iam.amazonaws.com/role: IoTDataAccess
    spec:
      containers:
      - image: chrisns/iot_velux
        name: velux-aws-iot
        command:
          - sh
          - -c
          - "`wget -qO- https://gist.githubusercontent.com/chrisns/4b732c4b2f85272aef6706d43e7063f8/raw/getiamcreds.js | node` && node index.js"
        imagePullPolicy: Always
        env:
          - name: VELUX_ADDRESS
            valueFrom:
              secretKeyRef:
                name: velux
                key: VELUX_ADDRESS
          - name: VELUX_PASSWORD
            valueFrom:
              secretKeyRef:
                name: velux
                key: VELUX_PASSWORD
          - name: VELUX_TOPIC
            valueFrom:
              secretKeyRef:
                name: velux
                key: VELUX_TOPIC
          - name: AWS_IOT_ENDPOINT_HOST
            value: a1o5j7svq7l99k.iot.eu-west-2.amazonaws.com
          - name: AWS_REGION
            value: eu-west-2
      restartPolicy: Always