apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml

secretGenerator:
  - name: velux
    env: env.txt
    type: Opaque

namespace: velux