apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  # - ble
  - broadlink
  - cameras
  - etcd-backup
  - kiam
  - magichome
  - metrics
  - nest
  - owlet
  - rules_engine
  - solaredge
  - sonos
  - velux
  - traefik
  # - reloader

secretGenerator:
  - name: aws-iot-creds
    env: aws-iot-creds.secret.txt
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true
