apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
spec:
  retention: 30d
  # retentionSize: 500GB
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: nfs
        resources:
          requests:
            storage: 100Gi
