kind: Deployment
apiVersion: apps/v1
metadata:
  name: zwave
spec:
  template:
    spec:
      containers:
        - name: zwave
          env:
            - name: BUCKET_KEY
              value: pink_usa
      nodeSelector:
        kubernetes.io/hostname: stick1
      volumes:
        - name: config
          secret:
            secretName: zwave2mqtt-usa
