nameSuffix: -usa
bases:
 - ../base

secretGenerator:
- name: zwave
  behavior: merge
  namespace: zwave
  env: env.txt
  type: Opaque

patches:
 - pvc.yaml
 - deployment.yaml

generatorOptions:
  disableNameSuffixHash: true