apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone
  namespace: drone
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  namespace: drone
  name: drone
subjects:
  - kind: ServiceAccount
    name: drone
    namespace: drone
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io