kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ble-eq3
  labels:
    name: ble-eq3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ble-eq3
  template:
    metadata:
      labels:
        name: ble-eq3
      annotations:
        iam.amazonaws.com/role: IoTDataAccess
    spec:
      hostNetwork: true
      containers:
      - image: chrisns/ble-eq3-awsiot
        name: ble-eq3
        command:
          - sh
          - -c
          - "`wget -qO- https://gist.githubusercontent.com/chrisns/4b732c4b2f85272aef6706d43e7063f8/raw/getiamcreds.js | node` && node index.js"
        imagePullPolicy: Always
        env:
          - name: AWS_IOT_ENDPOINT_HOST
            value: a1o5j7svq7l99k.iot.eu-west-2.amazonaws.com
          - name: AWS_REGION
            value: eu-west-2
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: stick4