kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zwave
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zwave
  template:
    metadata:
      labels:
        name: zwave
      annotations:
        iam.amazonaws.com/role: IoTZwave
    spec:
      containers:
        - image: chrisns/iot-zwave
          name: zwave
          # command:
          #   - sh
          #   - -c
          #   - "`wget -qO- https://gist.githubusercontent.com/chrisns/4b732c4b2f85272aef6706d43e7063f8/raw/getiamcreds.js | node` && node index.js"
          resources:
            limits:
              # cpu: 200m
              memory: 512Mi
            requests:
              # cpu: 100m
              memory: 400Mi
          volumeMounts:
            - mountPath: /dev/ttyUSB1
              name: zwavestick
            - mountPath: /data
              name: data
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
          env:
            - name: DEVICE
              value: /dev/ttyUSB1
            - name: DEBUG
              value: "true"
          envFrom:
            - secretRef:
                name: zwave
      restartPolicy: Always
      volumes:
        - name: zwavestick
          hostPath:
            path: /dev/ttyACM0
            type: File
        - name: data
          persistentVolumeClaim:
            claimName: zwave
