apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pv.yaml
  - pvc.yaml
  - deployment.yaml

secretGenerator:
  - name: zwave
    env: env.txt
    type: Opaque

namespace: zwave