apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml

configMapGenerator:
  - name: config
    files:
      - config/config.json

secretGenerator:
  - name: certs
    files:
      - certs/114a3a5ec0.private.key
      - certs/114a3a5ec0.cert.pem
      - certs/root.ca.pem
      - certs/114a3a5ec0.public.key

namespace: greengrass
