---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
  
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
      [entryPoints.ping]
      address = ":8082"
    [ping]
      entryPoint = "ping"
    [acme]
    email = "chris@cns.me.uk"
    Storage = "acme/acme.json"
    entryPoint = "https"
    # onDemand = true
    acmeLogging = true

    onHostRule = true
    [[acme.domains]]
    main = "*.p.cns.me"
    # sans = ["dashboard.p.cns.me"]
    [acme.dnsChallenge]
    provider = "godaddy"
    delayBeforeCheck = 0