apiVersion: v1
kind: PersistentVolume
metadata:
  name: acme-nfs
  namespace: kube-system
spec:
  capacity:
    storage: 10Mi
  storageClassName: acme-nfs
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.0.3
    path: /volume2/cluster-store/acme
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: traefik-ingress-pvc
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: acme-nfs
  resources:
    requests:
      storage: 10Mi
