kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: magicmirror
  labels:
    name: magicmirror
spec:
  replicas: 2
  selector:
    matchLabels:
      name: magicmirror
  template:
    metadata:
      labels:
        name: magicmirror
    spec:
      containers:      
      - image: pinked/magicmirror:bac9eca80c8fb5958f047973aad27486f8b3dd35
        name: magicmirror
        securityContext:
          runAsUser: 100
          readOnlyRootFilesystem: true
        resources:
          limits:
            memory: 12Mi
            cpu: 0.01
        ports:
         - name: http
           containerPort: 8080
        env:
          - name: MQTT_USER
            valueFrom:
              secretKeyRef:
                name: magicmirror-creds
                key: AWS_ACCESS_KEY_ID
          - name: MQTT_PASS
            valueFrom:
              secretKeyRef:
                name: magicmirror-creds
                key: AWS_SECRET_ACCESS_KEY
          - name: MQTT_HOST
            valueFrom:
              secretKeyRef:
                name: magicmirror-creds
                key: AWS_IOT_ENDPOINT_HOST
          - name: REGION
            valueFrom:
              secretKeyRef:
                name: magicmirror-creds
                key: AWS_REGION
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
      restartPolicy: Always
