kind: Deployment
apiVersion: apps/v1
metadata:
  name: zwave
spec:
  template:
    spec:
      containers:
        - name: zwave
          env:
            - name: BUCKET_KEY
              value: pink_eu
      nodeSelector:
        kubernetes.io/hostname: stick2
      volumes:
        - name: config
          secret:
            secretName: zwave2mqtt-eu
