kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: solaredge-aws-iot
  labels:
    name: solaredge-aws-iot
spec:
  replicas: 1
  selector:
    matchLabels:
      name: solaredge-aws-iot
  template:
    metadata:
      labels:
        name: solaredge-aws-iot
      annotations:
        iam.amazonaws.com/role: IoTDataAccess
    spec:
      containers:      
      - image: chrisns/iot-solaredge
        name: solaredge-aws-iot
        imagePullPolicy: Always
        command:
          - sh
          - -c
          - "`wget -qO- https://gist.githubusercontent.com/chrisns/4b732c4b2f85272aef6706d43e7063f8/raw/getiamcreds.js | node` && node index.js"
        env:
          - name: INTERVAL
            value: "120"
          - name: METERS
            value: "1"
          - name: SOLAREDGE_ENDPOINT
            value: "192.168.0.189"
          - name: AWS_IOT_ENDPOINT_HOST
            value: a1o5j7svq7l99k.iot.eu-west-2.amazonaws.com
          - name: AWS_REGION
            value: eu-west-2
      restartPolicy: Always