apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ingress.yaml
  - deployment.yaml
  - service.yaml

# commonLabels:
#   paths:
#     - path: metadata/labels
#       create: true

#     - path: spec/selector
#       create: true
#       version: v1
#       kind: Service

#     - path: spec/selector/matchLabels
#       create: true
#       kind: Deployment
#   labels:
#     app: foo

secretGenerator:
  - name: webrtc-config
    files:
      - config.json
  - name: webrtc
    env: env.txt
