kind: Deployment
apiVersion: apps/v1
metadata:
  name: sonos-aws-iot
  labels:
    name: sonos-aws-iot
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sonos-aws-iot
  template:
    metadata:
      labels:
        name: sonos-aws-iot
    spec:
      hostNetwork: true
      containers:
        - image: chrisns/sonos-aws-iot
          name: sonos-aws-iot
          resources:
            limits:
              memory: 256Mi
              cpu: 0.3
          env:
            - name: MQTT_PREFIX
              value: sonos/
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-iot-creds
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-iot-creds
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_IOT_ENDPOINT_HOST
              valueFrom:
                secretKeyRef:
                  name: aws-iot-creds
                  key: AWS_IOT_ENDPOINT_HOST
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-iot-creds
                  key: AWS_REGION
      restartPolicy: Always
