kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-remote-controller
  labels:
    name: traefik-ingress-remote
spec:
  replicas: 2
  selector:
    matchLabels:
      name: traefik-ingress-remote
  template:
    metadata:
      labels:
        name: traefik-ingress-remote
    spec:
      serviceAccountName: traefik-ingress-controller
      serviceAccount: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
        - image: traefik:v1.7
          name: traefik-ingress-remote
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /acme
              name: acme
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: admin
              containerPort: 8080
          args:
            - --api
            - --logLevel=INFO
            - --insecureskipverify
            - --configfile=/config/traefik.toml
          envFrom:
            - secretRef:
                name: traefik-ingress-controller-godaddy
          livenessProbe:
            httpGet:
              path: /ping
              port: 8082
            initialDelaySeconds: 3
            periodSeconds: 3
            timeoutSeconds: 1
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: role
                      operator: In
                      values:
                        - data
                topologyKey: kubernetes.io/hostname
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: traefik-remote-config
          name: config
        - name: acme
          persistentVolumeClaim:
            claimName: acme-remote
