defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
  [entryPoints.ping]
  address = ":8082"
[kubernetes]
  ingressClass = "traefik-remote"
[ping]
  entryPoint = "ping"
[acme]
email = "chris@cns.me.uk"
Storage = "acme/acme.json"
entryPoint = "https"
acmeLogging = true

onHostRule = true
[[acme.domains]]
main = "*.e.cns.me"
[acme.dnsChallenge]
provider = "godaddy"
delayBeforeCheck = 0