kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: owlet
  labels:
    name: owlet
spec:
  replicas: 1
  selector:
    matchLabels:
      name: owlet
  template:
    metadata:
      labels:
        name: owlet
    spec:
      containers:      
      - image: chrisns/owlet-iot
        name: owlet
        imagePullPolicy: Always
        env:
          - name: OWLET_USERNAME
            valueFrom:
              secretKeyRef:
                name: owlet
                key: OWLET_USERNAME
          - name: OWLET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: owlet
                key: OWLET_PASSWORD
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-iot-creds
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-iot-creds
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_IOT_ENDPOINT_HOST
            valueFrom:
              secretKeyRef:
                name: aws-iot-creds
                key: AWS_IOT_ENDPOINT_HOST
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: aws-iot-creds
                key: AWS_REGION
      restartPolicy: Always