apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - https://github.com/coreos/kube-prometheus
  - snmp

patches:
  - grafana/deployment-patch.yaml
  - prometheus/persisted-prometheus.yaml

resources:
  - grafana/pvc.yaml
  - ingress.yaml

generatorOptions:
  disableNameSuffixHash: true

namespace: monitoring
